xterm -hold -e 'python Lsr.py A 2000 configA.txt' &
xterm -hold -e 'python Lsr.py B 2001 configB.txt' &
xterm -hold -e 'python Lsr.py C 2002 configC.txt' &
xterm -hold -e 'python Lsr.py D 2003 configD.txt' &
xterm -hold -e 'python Lsr.py E 2004 configE.txt' &
xterm -hold -e 'python Lsr.py F 2005 configF.txt' &
xterm -hold -e 'python Lsr.py G 2006 configG.txt' &
xterm -hold -e 'python Lsr.py H 2007 configH.txt' &
xterm -hold -e 'python Lsr.py I 2008 configI.txt' &
xterm -hold -e 'python Lsr.py J 2009 configJ.txt' &